replicaCount: 2

image:
  repository: k3d-k3d-registry:5000/chat-app
  tag: "1.0.0_dev"
  pullPolicy: Always

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

service:
  type: ClusterIP
  port: 80

nodeSelector:
  env: nonprod
tolerations:
  - key: env
    operator: Equal
    value: nonprod
    effect: NoSchedule

logs:
  emptyDir: true
  pvc: ""

env: nonprod
terraformManagedService: false
