"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "labels":
    "component": "monitoring"
    "managed-by": "terraform"
    "project": "chat-app"
    "security.company": "chat-app"
    "security.environment": "dev"
    "security.managed-by": "terraform"
    "security.version": "1.0.0"
    "terraform": "true"
  "name": "opentelemetry-collector"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "monitoring"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "opentelemetry-collector"
    "helm":
      "releaseName": "otel-collector"
      "values":
        "config":
          "exporters":
            "loki":
              "endpoint": "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
            "prometheus":
              "endpoint": "0.0.0.0:8889"
            "tempo":
              "endpoint": "http://tempo.monitoring.svc.cluster.local:4317"
          "processors":
            "batch": {}
            "memory_limiter":
              "limit_mib": 512
            "resource":
              "attributes":
              - "key": "environment"
                "value": "dev"
          "receivers":
            "otlp":
              "protocols":
                "grpc":
                  "endpoint": "0.0.0.0:4317"
                "http":
                  "endpoint": "0.0.0.0:4318"
            "prometheus":
              "config":
                "scrape_configs":
                - "job_name": "kubernetes-pods"
                  "kubernetes_sd_configs":
                  - "role": "pod"
                  "relabel_configs":
                  - "action": "keep"
                    "regex": "true"
                    "source_labels":
                    - "__meta_kubernetes_pod_annotation_prometheus_io_scrape"
                  - "action": "replace"
                    "regex": "(.+)"
                    "source_labels":
                    - "__meta_kubernetes_pod_annotation_prometheus_io_path"
                    "target_label": "__metrics_path__"
          "service":
            "pipelines":
              "logs":
                "exporters":
                - "loki"
                "processors":
                - "memory_limiter"
                - "batch"
                "receivers":
                - "otlp"
              "metrics":
                "exporters":
                - "prometheus"
                "processors":
                - "memory_limiter"
                - "batch"
                "receivers":
                - "otlp"
                - "prometheus"
              "traces":
                "exporters":
                - "tempo"
                "processors":
                - "memory_limiter"
                - "batch"
                "receivers":
                - "otlp"
        "mode": "deployment"
    "repoURL": "https://open-telemetry.github.io/helm-charts"
    "targetRevision": "latest"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": false
    "syncOptions":
    - "CreateNamespace=true"
