"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "labels":
    "component": "monitoring"
    "managed-by": "terraform"
    "project": "chat-app"
    "security.company": "chat-app"
    "security.environment": "dev"
    "security.managed-by": "terraform"
    "security.version": "1.0.0"
    "terraform": "true"
  "name": "tempo"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "tempo"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "kustomize":
      "images":
      - "name": "tempo"
        "newTag": "latest"
    "path": "platform/manifests/monitoring"
    "repoURL": "https://github.com/dmitri166/chat-gitops-on_prem"
    "targetRevision": "master"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
    "syncOptions":
    - "CreateNamespace=true"
