apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}

{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}

      containers:
        - name: chat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 8000
              name: metrics

{{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}

{{- if .Values.env }}
          env:
            - name: ENV
              value: "{{ .Values.env }}"
{{- end }}

          volumeMounts:
            - name: logs
              mountPath: /app/logs

      volumes:
        - name: logs
{{- if .Values.logs.pvc }}
          persistentVolumeClaim:
            claimName: {{ .Values.logs.pvc }}
{{- else }}
          emptyDir: {}
{{- end }}
