apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      containers:
      - name: chat
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 8000
          name: metrics
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        resources: {{ toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: chat-logs-{{ .Release.Namespace | replace "chat-" "" | replace "-ns" "" }}
