apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 6 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 6 }}
      containers:
      - name: chat
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 8000
          name: metrics
        resources:
        {{- if .Values.resources }}
        {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
        env:
        {{- if .Values.env }}
        {{- range $key, $val := dict "ENV" .Values.env }}
          - name: {{ $key }}
            value: "{{ $val }}"
        {{- end }}
        {{- end }}
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        {{- if .Values.logs.pvc }}
        persistentVolumeClaim:
          claimName: {{ .Values.logs.pvc }}
        {{- else if .Values.logs.emptyDir }}
        emptyDir: {}
        {{- end }}