apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ghost-platform-complete
  namespace: argocd
  labels:
    app.kubernetes.io/name: ghost-platform
    app.kubernetes.io/component: applicationset
    app.kubernetes.io/part-of: ghost-platform
spec:
  generators:
    # MySQL Infrastructure Generator
    - list:
        elements:
          - name: mysql
            namespace: ghost
            path: infrastructure/mysql/helm
            valuesFile: values.yaml
            
    # Ghost Environments Generator
    - list:
        elements:
          - env: dev
            namespace: ghost
            path: applications/ghost-app/helm
            valuesFile: values-dev.yaml
          - env: staging
            namespace: ghost
            path: applications/ghost-app/helm
            valuesFile: values-staging.yaml
          - env: prod
            namespace: ghost
            path: applications/ghost-app/helm
            valuesFile: values-prod.yaml
            
  template:
    metadata:
      name: '{{name}}-{{env}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: ghost
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: ghost-platform
        app.kubernetes.io/environment: '{{env}}'
      annotations:
        argocd.argoproj.io/sync-options: CreateNamespace=true
        argocd.argoproj.io/compare-options: IgnoreExtraneousFields
        
    spec:
      project: ghost-apps
      
      source:
        repoURL: https://github.com/dmitri166/ghost_on_prem_project
        targetRevision: master
        path: '{{path}}'
        helm:
          valueFiles:
            - '{{valuesFile}}'
          parameters:
            # Ghost-specific parameters (only for Ghost apps)
            - name: global.environment
              value: '{{env}}'
            - name: replicaCount
              value: '{{env}}'
            - name: image.tag
              value: '5.75.1'
            - name: service.port
              value: '2368'
            - name: serviceAccount.create
              value: 'true'
            - name: serviceAccount.name
              value: '{{name}}-{{env}}'
            - name: ingress.enabled
              value: 'true'
            - name: ingress.hosts[0].host
              value: '{{name}}-{{env}}.local'
            - name: ingress.hosts[0].paths[0].path
              value: '/'
            - name: ingress.hosts[0].paths[0].pathType
              value: Prefix
            - name: resources.requests.cpu
              value: '100m'
            - name: resources.requests.memory
              value: '128Mi'
            - name: resources.limits.cpu
              value: '500m'
            - name: resources.limits.memory
              value: '512Mi'
            - name: persistence.enabled
              value: 'true'
            - name: persistence.size
              value: '10Gi'
            - name: mysql.enabled
              value: 'false'
            - name: database.client
              value: 'mysql'
            - name: database.connection.host
              value: 'mysql.ghost.svc.cluster.local'
            - name: database.connection.port
              value: '3306'
            - name: database.connection.user
              value: 'ghost'
            - name: database.connection.password
              value: 'ghost123'
            - name: database.connection.database
              value: 'ghost'
            - name: ghost.config.url
              value: 'http://{{name}}-{{env}}.local:2368'
            - name: ghost.config.adminUrl
              value: 'http://{{name}}-{{env}}.local:2368/ghost'
            - name: ghost.config.contentUrl
              value: 'http://{{name}}-{{env}}.local:2368/content'
            - name: monitoring.enabled
              value: 'true'
            - name: monitoring.serviceMonitor
              value: 'true'
            - name: security.podSecurityContext.runAsNonRoot
              value: 'true'
            - name: security.podSecurityContext.runAsUser
              value: '1000'
            - name: security.podSecurityContext.fsGroup
              value: '2000'
            
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
        
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
            
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
